name: Deploy on Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Services
        run: docker compose up -d

      - name: Check Running Containers
        run: docker ps